= Parameters

The parent key for all of the following parameters is `cloudscale_cloud_controller_manager`.

== `namespace`

[horizontal]
type:: string
default:: `syn-cloudscale-cloud-controller-manager`

The namespace in which to deploy this component.

== `manifests_version`

[horizontal]
type:: string
defaults:: `${cloudscale_cloud_controller_manager:images:cloudscale_cloud_controller_manager:tag}`

[IMPORTANT]
====
This parameter is deprecated.
Users should use parameter `images.cloudscale_cloud_controller_manager.tag` to select the manifests version that the component uses.
====

The cloudscale CCM version to deploy.

== `images`

[horizontal]
type:: object
defaults:: [See `class/defaults.yml`]

The container images to use.

NOTE: The component uses the value of `images.cloudscale_cloud_controller_manager.tag` when downloading the upstream manifests which form the base for the manifests generated by the component.

== `args`

[horizontal]
type:: list
defaults:: `[]`

Additional arguments to provide to the cloudscale CCM.
The contents of this parameter are appended to the upstream manifest verbatim.

== `api_token`

[horizontal]
type:: string
default:: `?{vaultkv:${cluster:tenant}/${cluster:name}/cloudscale/token}`

cloudscale.ch API token to be used by the CCM driver.
This should be a reference to a secret in Vault instead of the plaintext token.


== Example

[source,yaml]
----
namespace: example-namespace
----
