= Parameters

The parent key for all of the following parameters is `cloudscale_cloud_controller_manager`.

== `namespace`

[horizontal]
type:: string
default:: `syn-cloudscale-cloud-controller-manager`

The namespace in which to deploy this component.

== `manifests_version`

[horizontal]
type:: string
defaults:: `${cloudscale_cloud_controller_manager:images:cloudscale_cloud_controller_manager:tag}`

[IMPORTANT]
====
This parameter is deprecated.
Users should use parameter `images.cloudscale_cloud_controller_manager.tag` to select the manifests version that the component uses.
====

The cloudscale CCM version to deploy.

== `images`

[horizontal]
type:: object
defaults:: [See `class/defaults.yml`]

The container images to use.

NOTE: The component uses the value of `images.cloudscale_cloud_controller_manager.tag` when downloading the upstream manifests which form the base for the manifests generated by the component.

== `args`

[horizontal]
type:: list
defaults:: `[]`

Additional arguments to provide to the cloudscale CCM.
The contents of this parameter are appended to the upstream manifest verbatim.

== `api_timeout_seconds`

[horizontal]
type:: number
default:: `null`

The API timeout to be used by the CCM driver when communicating with the cloudscale.ch API.
Unit is seconds.
If not set the CCM driver will use its upstream default.

The current upstream timeout default is 20 seconds (https://github.com/cloudscale-ch/cloudscale-cloud-controller-manager/blob/74832bae401dc0fc79dcfba923ae154eac684779/pkg/cloudscale_ccm/cloud.go#L28[upstream code]).

== `api_token`

[horizontal]
type:: string
default:: `?{vaultkv:${cluster:tenant}/${cluster:name}/cloudscale/token}`

cloudscale.ch API token to be used by the CCM driver.
This should be a reference to a secret in Vault instead of the plaintext token.


== Example

[source,yaml]
----
namespace: example-namespace
----
